name: action_teste

inputs:
  nome:
    id: nome
    description: nome
    required: true
    default: indigente

# outputs:
#   NOME_OUTPUT:
#     description: A
#     value: A

runs:
  using: composite
  steps:
    - name: echo
      if: ${{ nome != 'indigente' }}
      shell: bash
      run: echo ${{ inputs.nome }}
    # - name: NAME_STEP
    #   if: EXPRESSAO
    #   var:
    #     VAR1: VALUE1
    #   working-directory: A
    #   run: COMANDO OU PATH_EXECUTAVEL
    #   shell: bash
    #   uses: PODE_USAR_OUTRA_ACTION
    #   with:
    #     ...