name: action_teste

inputs:
  nome:
    id: nome
    description: nome
    required: true
    default: indigente

runs:
  using: composite
  steps:
    - name: echo
      if: ${{ inputs.nome != 'indigente' }}
      shell: bash
      run: |
        echo ${{ inputs.nome }}
        echo VARIAVEL_EXTERNA=${{ inputs.nome }} >> $GITHUB_ENV
