name: workflow
on:
  workflow_dispatch:
    inputs:
      nome:
        required: true
        default: indigente
        type: string
      numero_string:
        default: 77
        required: false
        type: string

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: pegar o codigo
        uses: actions/checkout@v4
      - name: usar action
        uses: ./.github/actions/echo/
        with:
          nome: ${{inputs.nome}}
      - name: teste
        run: |
          echo "numero_string="${{inputs.numero_string}} \
            "ele também é multiline"
