name: name_workflow
on:
  workflow_dispatch:
    inputs:
      nome:
        required: true
        default: indigente
        type: string

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: pegar o codigo
        uses: actions/checkout@v4
      - name: usar action
        uses: ./.github/actions/echo/
        with:
          nome: ${{inputs.nome}}