name: workflow
on:
  workflow_dispatch:
    inputs:
      nome:
        required: true
        default: indigente
        type: string
      teste:
        required: false
        type: choice
        options:
          - um
          - dois

jobs:
  teste:
    env:
      testando: funciona
    runs-on: ubuntu-latest
    steps:
      # - name: pegar o codigo
      #   uses: actions/checkout@v4
      # - name: usar action
      #   if: "${{ github.event.inputs.nome == 'gabriel' }}"
      #   uses: ./.github/actions/echo/
      #   with:
      #     nome: ${{inputs.nome}}
      # - name: teste_choice
      #   run: |
      #     echo ${{inputs.teste}}
      # - name: teste_if
      #   run: |
      #     if [[ ${{inputs.nome}} == "gabriel" ]]; then
      #       export NOME_VAR=${{env.testando}}
      #       echo $NOME_VAR
      #       echo 'foi no if'
      #     elif [[ ${{inputs.nome}} == "pedro" ]] && [[ ${{inputs.teste}} == "doi"* ]]; then
      #       export NOME_VAR=${{env.testando}}
      #       echo $NOME_VAR
      #       echo 'foi no elif'
      #     else
      #       echo "Caiu no else"
      #     fi
      - name: teste mudar input
        run: |
          if [[ ${{inputs.nome}} =~ "gabriel" ]]; then
              ${{inputs.nome}}="teste"
              export vamosver=teste
              echo 'caiu no if!'
          fi
      - name: print nome
        run: |
          echo ${{inputs.nome}}
          echo $vamosver
      - name: mascarar senha
        run: |
          PASSWORD=$(jq -r '.inputs.nome' $GITHUB_EVENT_PATH)
          echo ::add-mask::$PASSWORD
          echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV
      - name: verificar
        run: |
          echo ${{ env.PASSWORD }}
          if [[ ${{env.PASSWORD}} == 'gabriel' ]]; then
            echo 'sim'
          fi