name: workflow
on:
  workflow_dispatch:
    inputs:
      nome:
        required: true
        default: indigente
        type: string
      teste:
        required: false
        type: choice
        options:
          - um
          - dois

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: pegar o codigo
        uses: actions/checkout@v4
      - name: usar action
        if: "${{ github.event.inputs.nome == 'gabriel' }}"
        uses: ./.github/actions/echo/
        with:
          nome: ${{inputs.nome}}
      - name: validação
        env:
          nomes: ['João', 'Pedro', 'Joaquim']
        run: |
          echo ${{ toJSON(env.nomes) }}

          for item in ${{ toJSON(env.nomes) }}; do
            echo $item
          done
