name: name_workflow
on: workflow_dispatch

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: pegar o codigo
        uses: actions/checkout@v4
      - name: usar action
        uses: ./.github/actions/echo/
        with:
          nome: Joaquim