name: workflow
on:
  workflow_dispatch:
    inputs:
      nome:
        required: true
        default: indigente
        type: string
      teste:
        required: false
        type: choice
        options:
          - um
          - dois

jobs:
  teste:
    env:
      testando: funciona
    runs-on: ubuntu-latest
    steps:
      - name: pegar o codigo
        uses: actions/checkout@v4
      - name: usar action
        uses: ./.github/actions/echo/
        with:
          nome: ${{inputs.nome}}
      - name: teste_choice
        run: |
          echo ${{inputs.teste}}
      - name: teste_if
        run: |
          if [[ ${{inputs.nome}} == "gabriel" ]]; then
            export NOME_VAR=${{env.testando}}
            echo $NOME_VAR
            echo 'foi no if'
          elif [[ ${{inputs.nome}} == "pedro" ]] && [[ ${{inputs.choice}} == "doi"* ]]; then
            export NOME_VAR=${{env.testando}}
            echo $NOME_VAR
            echo 'foi no elif'
          else
            echo "Caiu no else"
          fi
